# Generated by Django 4.0.3 on 2022-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(choices=[('Танки', 'Танки'), ('Хилы', 'Хилы')], max_length=255, unique=True),
        ),
    ]
