# Generated by Django 4.0.3 on 2022-04-07 21:08

from django.db import migrations, models
import django.utils.timezone
import myboardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myboardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='file_uploader',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name=models.FileField(blank=True, null=True, upload_to=myboardapp.models.user_directory_path, verbose_name='File Upload')),
            preserve_default=False,
        ),
    ]
