# Generated by Django 4.0.4 on 2022-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
