# Generated by Django 4.0.3 on 2022-04-10 20:12

from django.db import migrations, models
import myboardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myboardapp', '0002_remove_bulletin_file_uploader_bulletin_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='file',
            field=models.FileField(blank=True, upload_to=myboardapp.models.user_directory_path, verbose_name='File Upload'),
        ),
    ]
