# Generated by Django 4.0.3 on 2022-04-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myboardapp', '0004_rename_user_usualuser_alter_bulletin_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsualUser',
        ),
    ]
