# Generated by Django 4.0.3 on 2022-04-10 20:45

from django.db import migrations, models
import myboardapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myboardapp', '0005_delete_usualuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='file',
            field=models.FileField(blank=True, upload_to=myboardapp.models.user_directory_path),
        ),
    ]
