"""
Django settings for Bboard project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o272xl4+_@h%zyd2ju3q4^(1-=e!xi9i^9m&)_dp)!lhctz2(m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# .replit
ALLOWED_HOSTS = [
    '127.0.0.1',
    # 'bulletinboard.exp.repl.co',
    # 'f2a74711-d7cc-4b7a-805f-db5cf7fe2928.id.repl.co',
]

CSRF_TRUSTED_ORIGINS = [
'https://bulletinboard.exp.repl.co',
'https://f2a74711-d7cc-4b7a-805f-db5cf7fe2928.id.repl.co',	
]


# Application definition

INSTALLED_APPS = [
    'myboardapp.apps.MyboardappConfig', # my application
    'users.apps.UsersConfig', # my application
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Bboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# The location to saving uploaded files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Any files were uploaded will be show up under this path
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# pip install django-crispy-forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'





# authorisation/authentification

# allauth application
INSTALLED_APPS += [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]
SITE_ID = 1


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# redirect authenticated users to LOGIN_REDIRECT_URL if True
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
# redirect user to a home page after logging in
LOGIN_REDIRECT_URL = 'home'


ACCOUNT_AUTHENTIFICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
# True позволит избежать дополнительных действий и активирует аккаунт сразу, как только мы перейдем по ссылке
# False попросит подтвердить ещё раз на сайте после прохождения по ссылке
ACCOUNT_CONFIRM_EMAIL_ON_GET = True


# подтверждение аккаунта через письмо на почту
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_UNIQUE_EMAIL = True

# тема письма для подтверждения регистрации
ACCOUNT_EMAIL_SUBJECT_PREFIX = "From Bulat with regards. "
# поле username необязательно
ACCOUNT_USERNAME_REQUIRED = False

# количество дней, в течение которых будет доступна ссылка на подтверждение регистрации
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = 'profile'
# чтобы allauth выполнил именно эту форму при регистрации пользователя,
# а не ту, что по умолчанию, напишем:
ACCOUNT_FORMS = {'/accounts/signup': 'users.forms.UserUpdateForm'}


# a user will get confirmation e-mails from the following adress
DEFAULT_FROM_EMAIL = 'FPW-13@yandex.ru'
EMAIL_HOST = 'smtp.yandex.ru'  # адрес сервера Яндекс-почты для всех один и тот же
EMAIL_PORT = 465  # порт smtp сервера тоже одинаковый
EMAIL_HOST_USER = 'FPW-13'  # ваше имя пользователя, например, если ваша почта user@yandex.ru, то сюда надо писать user, иными словами, это всё то что идёт до собаки
EMAIL_HOST_PASSWORD = 'dV8-Zxg-ebQ-wZ3'  # пароль от почты
EMAIL_USE_SSL = True  # Яндекс использует ssl, подробнее о том, что это, почитайте в дополнительных источниках, но включать его здесь обязательно


# если пользователь вышел, его перенаправит на страницу:
LOGOUT_REDIRECT_URL = '/accounts/login/'

# redirect user to a login page if he wants to access to a login required page
LOGIN_URL = '/accounts/login/' # url pattern name

